language: node_js
node_js:
- '6'
install:
- npm install
script: npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: mt.franchetto@gmail.com
  api_key:
    secure: bdFa4U+sBQqgBLwpVgEnqNv0tlVtfoYa/YXy9TfVhZL6Y1aHN7B253g0f8Khzpl0AokPYO51Q4mOZcO6ijcC7IZtCAvWl5Ek4bE5jEMiI/73Gf3zXINetmK6354BeGyHTEiAcfo01X3IBc7dkdUE4+7dciHR+/Yqw2rRFRyQ7JufvjTNZ7zNZYSHocH46408gpfCT8x99+09T2FOS4fkn22bUgZPg+mYgYT8DPaFZFNhRBr1Gb52+nDGDXXAxO2gNLkaxEL+O/X4K+wkH7GiS07+9TulUqfRimuhOv9z6Gawe0Zio2vUocjMHh9NV4BaAUU0f5mtZJDuSAUOOn9UsBg4RxfzvPMA0Ytg6mfa2esESlYeuOimWPK/hIjWJ3pbTLB5S06tJW3eqXJ+YEkJ1cyhJSik2RDFvU+vWcqy+zbJMJsHfgTUJlk98MlPcoEU9C/YYZxMb2w7+Ihh2vNfylsjzR5AXjdg4mM43sOaQUcU4vhVkkm7l6RmB7N0mVAE3WLcQhYYXC9Uf9/AIzC+s/kvp2Z3Led5V30CzwBT6RHP5ebvAbuLgUepNYcus1mZsGmUWoMbMWrXhTUwWSxuw/UPhVN1/2f6dkVWUOinrkUB1j3aiwcgsIvAhr6nWecSoApmrY6Zp+Z2tYCaBxP+JMoMKJ2bv5I4LMnvGEY41B4=
  on:
    repo: mtfranchetto/smild
    tags: true
